### PR TITLE
Migration to es6

### PR DESCRIPTION
**Pull request by grafixeyehero**
deppend on this https://github.com/jellyfin/jellyfin-web/pull/2707 to **Access module**

### CODE REVIEW

**Review by crobibero — APPROVED** [review]
Assumed tested.

**Comment by khimaros** [comment]
@grafixeyehero -- are you still planning to merge this change?

**Comment by gopaljigaur** [comment]
It is going to be almost two months since this request was last updated. Please fast-track this as this can make the Auto Organize plugin finally work.

**Comment by Sythelux** [comment]
> deppend on this [jellyfin/jellyfin-web#2707](https://github.com/jellyfin/jellyfin-web/pull/2707) to **Access module**

the jellyfin-web feature just got merged 3 mins ago.

**Comment by crobibero** [comment]
> > deppend on this [jellyfin/jellyfin-web#2707](https://github.com/jellyfin/jellyfin-web/pull/2707) to **Access module**
> 
> the jellyfin-web feature just got merged 3 mins ago.

Thank you for the update, but we cannot release this until Jellyfin 10.8 is out as that’s when the web changes will be released.

**Review by sbranden — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Pull request merged**
